// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cekegswjtmiiqlpsghcr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNla2Vnc3dqdG1paXFscHNnaGNyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM5MTQyMjcsImV4cCI6MjA2OTQ5MDIyN30.thxbBs0HpkmJn0E0HHahTYKTkeGotnTgcOhoOGXzgJY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});